fieldtype_fields:
  mode:
    type: select
    default: table
    options:
      table: Table
      stacked: Stacked
  max_rows:
    type: integer
  min_rows:
    type: integer
  add_row:
    type: text
  fields:
    type: fields
